### ISSUE TITLE
Css syntax is broken after update

### ISSUE THREAD

**Issue by felixcatto** [SublimeText/TailwindCSS#7] opened 2023-05-06 03:05 UTC
**Sublime version: 4143**

Seems after last update the syntax is broken.
In `css` syntax all works fine except nested rules

![before](https://user-images.githubusercontent.com/6022888/236595141-ae640ddc-c2d9-41cd-ba45-2fa3f6bd3df1.png)

In `tailwind css` before update all works fine, but now css and nested rules are broken

![after](https://user-images.githubusercontent.com/6022888/236595228-56f2e655-afb1-4e4f-a30c-63ce5bc3103e.png)

To be honest the Tailwind syntax support is not critical for me. If it stays gray and doesn't highlighted / autocompleted - not a big problem.

But i desperately need modern ST4 css syntax and nested rules, and it is the only package which have such behavior.

**Comment by deathaxe** [comment] 2023-05-06 08:50
Thank's for reporting.

The more generic approach of supporting nested rules was missing some relevant changes from ST 4149's new CSS syntax.

The issue is fixed by v1.3.1 and should land soon on packagecontrol.io

**Closed as completed** 2023-05-06 08:51 UTC
Labels: bug
